// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Removing the above comment will disable type generation for this module
// This file was created by @hubspot/cms-dev-server, for more information see https://github.hubspot.com/cms-react/reference/js-modules.html#module-fields
import { type LogoFieldType, type FieldGroupWithChildren, type MenuFieldType, type RequiredField, type BooleanFieldType, type TextFieldType, type LinkFieldType, type DefaultValues } from "@hubspot/cms-components/fields";
type SiteHeaderFieldsType = DefaultValues<{
    groupLogo: FieldGroupWithChildren<{
        logo?: LogoFieldType;
    }>;
    menu: RequiredField<MenuFieldType>;
    groupActions: FieldGroupWithChildren<{
        showPrimaryAction?: BooleanFieldType;
        groupPrimaryAction: FieldGroupWithChildren<{
            primaryActionText: RequiredField<TextFieldType>;
            primaryActionLink?: LinkFieldType;
        }>;
        showSecondaryAction?: BooleanFieldType;
        groupSecondaryAction: FieldGroupWithChildren<{
            secondaryActionText: RequiredField<TextFieldType>;
            secondaryActionLink?: LinkFieldType;
        }>;
    }>;
}>;
export default SiteHeaderFieldsType;